apiVersion : v1
kind : Service
metadata :
  name : app1
spec :
  selector :
    name : app1
  ports :
    - port : 8080
      targetPort : 8080


---

apiVersion : v1
kind : Service
metadata :
  name : app2
spec :
  selector :
    name : app2
  ports :
    - port : 8080
      targetPort : 8080
"service.yml" 24L, 295B 